@extends('layout') @section('title','Edit '.$application->reference) @section('content')
<div class="section-head"><div><div class="eyebrow">EDIT SUBMITTED APPLICATION</div><h1>{{ $application->reference }}</h1><p class="subtitle">Update customer and device details before the application is reviewed.</p></div><a href="/applications/{{ $application->public_id }}">Cancel</a></div>
<script type="application/json" id="tanzania-locations">@json($locations)</script>
<form method="POST" action="/applications/{{ $application->public_id }}">@csrf @method('PUT')
<section class="panel"><h2>Customer KYC</h2><div class="grid two"><label>Full name<input name="name" required value="{{ old('name',$application->customer->name) }}"></label><label>NIDA or ID number<input name="id_number" required value="{{ old('id_number',$application->id_number) }}"></label><label>Date of birth<input name="date_of_birth" type="date" max="{{ today()->subDay()->toDateString() }}" required value="{{ old('date_of_birth',$application->customer->date_of_birth?->toDateString()) }}"></label><label>Gender<select name="gender" required><option value="male" @selected(old('gender',$application->customer->gender)==='male')>Male</option><option value="female" @selected(old('gender',$application->customer->gender)==='female')>Female</option></select></label><label>Mobile number<input name="phone" required value="{{ old('phone',$application->phone) }}"></label><label>Alternative number<input name="alternative_phone" value="{{ old('alternative_phone',$application->customer->alternative_phone) }}"></label><label>Email address<input name="email" type="email" required value="{{ old('email',$application->customer->email) }}"></label></div></section>
<section class="panel"><h2>Address & next of kin</h2><div class="grid two"><label>Region<select name="region" id="region" required data-selected="{{ old('region',$application->customer->region) }}"><option value="">Select region</option></select></label><label>District<select name="district" id="district" required data-selected="{{ old('district',$application->customer->district) }}"><option value="">Select district</option></select></label><label>Ward<select name="ward" id="ward" required data-selected="{{ old('ward',$application->customer->ward) }}"><option value="">Select ward</option></select></label><label class="full-span">Customer address<textarea name="customer_address" required>{{ old('customer_address',$application->customer->address) }}</textarea></label><label>Occupation or business<input name="occupation" required value="{{ old('occupation',$application->customer->occupation) }}"></label><label>Next of kin<input name="next_of_kin" required value="{{ old('next_of_kin',$application->customer->next_of_kin) }}"></label><label>Next-of-kin mobile number<input name="next_of_kin_phone" required value="{{ old('next_of_kin_phone',$application->customer->next_of_kin_phone) }}"></label></div></section>
<section class="panel"><h2>Meter details</h2><div class="grid two"><label>Utility type<select name="utility_type" required><option value="electricity" @selected(old('utility_type',$application->utility_type)==='electricity')>Electricity</option><option value="water" @selected(old('utility_type',$application->utility_type)==='water')>Water</option></select></label><label>Device price (TZS)<input name="device_price" type="number" min="1" required value="{{ old('device_price',$application->device_price) }}"></label><label>Meter brand or model<input name="meter_brand_model" required value="{{ old('meter_brand_model',$application->meter_brand_model) }}"></label><label>Serial number<input name="device_serial" value="{{ old('device_serial',$application->device_serial) }}"></label><label class="full-span">Installation address<textarea name="installation_address" required>{{ old('installation_address',$application->address) }}</textarea></label><label>Installation date<input name="installation_date" type="date" value="{{ old('installation_date',$application->installation_date) }}"></label></div><label class="check-label"><input type="checkbox" name="quotation_attached" value="1" required @checked(old('quotation_attached',$application->quotation_attached))>Device quotation or order has been checked and attached.</label></section>
<button>Save application changes</button> <a href="/applications/{{ $application->public_id }}">Cancel</a></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const locations=JSON.parse(document.getElementById('tanzania-locations').textContent),region=document.getElementById('region'),district=document.getElementById('district'),ward=document.getElementById('ward');const fill=(select,items,placeholder,selected='')=>{select.innerHTML='<option value="">'+placeholder+'</option>';items.forEach(item=>select.add(new Option(item,item,false,item===selected)));select.disabled=!items.length};fill(region,Object.keys(locations),'Select region',region.dataset.selected);const loadDistricts=selected=>fill(district,Object.keys(locations[region.value]||{}),'Select district',selected);const loadWards=selected=>fill(ward,(locations[region.value]||{})[district.value]||[],'Select ward',selected);region.addEventListener('change',()=>{loadDistricts('');fill(ward,[],'Select ward')});district.addEventListener('change',()=>loadWards(''));if(region.value){loadDistricts(district.dataset.selected);if(district.value)loadWards(ward.dataset.selected)}});</script>
@endsection
