@extends('layout') @section('title',$application->reference) @section('content')
<div class="section-head"><div><div class="eyebrow">APPLICATION PROFILE</div><h1>{{ $application->reference }}</h1><p class="subtitle">Submitted {{ $application->created_at->format('d M Y, H:i') }}</p></div><div class="inline">@if(auth()->user()->role==='supplier' && $application->status==='submitted')<a class="button" href="/applications/{{ $application->public_id }}/edit">✎ Edit</a>@endif<span class="badge {{ $application->status }}">{{ ucfirst($application->status) }}</span></div></div>
<div class="grid two"><section class="panel"><h2>Customer KYC</h2><dl class="profile-list"><div><dt>Full name</dt><dd>{{ $application->customer->name }}</dd></div><div><dt>ID type</dt><dd>{{ ['national_id'=>'National ID','driving_license'=>'Driving License','passport'=>'Passport','voters_id'=>'Voters ID'][$application->id_type] ?? 'National ID' }}</dd></div><div><dt>Identification number</dt><dd>{{ $application->id_number }}</dd></div><div><dt>Date of birth</dt><dd>{{ $application->customer->date_of_birth?->format('d M Y') ?: '—' }}</dd></div><div><dt>Gender</dt><dd>{{ ucfirst($application->customer->gender ?: '—') }}</dd></div><div><dt>Mobile number</dt><dd>{{ $application->phone }}</dd></div><div><dt>Alternative number</dt><dd>{{ $application->customer->alternative_phone ?: '—' }}</dd></div><div><dt>Email</dt><dd>{{ $application->customer->email }}</dd></div><div><dt>Occupation / business</dt><dd>{{ $application->customer->occupation ?: '—' }}</dd></div></dl></section>
<section class="panel"><h2>Address & next of kin</h2><dl class="profile-list"><div><dt>Region</dt><dd>{{ $application->customer->region ?: '—' }}</dd></div><div><dt>District</dt><dd>{{ $application->customer->district ?: '—' }}</dd></div><div><dt>Ward</dt><dd>{{ $application->customer->ward ?: '—' }}</dd></div><div><dt>Address</dt><dd>{{ $application->customer->address ?: '—' }}</dd></div><div><dt>Next of kin</dt><dd>{{ $application->customer->next_of_kin ?: '—' }}</dd></div><div><dt>Next-of-kin phone</dt><dd>{{ $application->customer->next_of_kin_phone ?: '—' }}</dd></div><div><dt>Onboarded by</dt><dd>{{ $application->customer->onboardedBy?->name ?: 'Self-registered' }}</dd></div></dl></section></div>
<div class="grid two"><section class="panel"><h2>Meter details</h2><dl class="profile-list"><div><dt>Utility type</dt><dd>{{ ucfirst($application->utility_type ?: '—') }}</dd></div><div><dt>Device price</dt><dd>{{ $application->device_price ? number_format($application->device_price).' TZS' : '—' }}</dd></div><div><dt>Brand / model</dt><dd>{{ $application->meter_brand_model ?: '—' }}</dd></div><div><dt>Serial number</dt><dd>{{ $application->device_serial ?: 'Not assigned' }}</dd></div><div><dt>Installation address</dt><dd>{{ $application->address }}</dd></div><div><dt>Installation date</dt><dd>{{ $application->installation_date ? \Carbon\Carbon::parse($application->installation_date)->format('d M Y') : 'Not scheduled' }}</dd></div><div><dt>Quotation / order</dt><dd>{{ $application->quotation_attached ? 'Confirmed attached' : 'Not confirmed' }}</dd></div></dl></section>
<section class="panel"><h2>Loan details</h2>@php($t=$application->terms)<dl class="profile-list"><div><dt>Product</dt><dd>{{ $t['product_name'] }}</dd></div><div><dt>Device value</dt><dd>{{ number_format($t['value']) }} TZS</dd></div><div><dt>Total upfront</dt><dd>{{ number_format($t['upfront']) }} TZS</dd></div><div><dt>Total repayable</dt><dd>{{ number_format($t['repayment_total']) }} TZS</dd></div><div><dt>Monthly instalment</dt><dd>{{ number_format(intdiv($t['repayment_total'],$t['installments'])) }} TZS</dd></div><div><dt>Tenure</dt><dd>{{ $t['installments'] }} months</dd></div><div><dt>Terms accepted</dt><dd>{{ $application->accepted_at->format('d M Y, H:i') }}</dd></div></dl></section></div>
@if($application->decision_reason)<div class="panel"><h2>Decision reason</h2><p>{{ $application->decision_reason }}</p></div>@endif
@if($application->upfrontPayment)@php($upfrontStatus=$application->loan?$application->loan->payments()->where('reference',$application->upfrontPayment->reference)->value('status'):'pending')<div class="panel"><div class="section-head"><h2>Upfront payment recorded</h2><span class="badge {{ $upfrontStatus ?: 'pending' }}">{{ ucfirst($upfrontStatus ?: 'pending') }}</span></div><dl class="profile-list"><div><dt>Amount</dt><dd>{{ number_format($application->upfrontPayment->amount) }} TZS</dd></div><div><dt>Reference</dt><dd>{{ $application->upfrontPayment->reference }}</dd></div><div><dt>Channel</dt><dd>{{ str_replace('_',' ',$application->upfrontPayment->channel) }}</dd></div><div><dt>Payment date</dt><dd>{{ $application->upfrontPayment->paid_at->format('d M Y') }}</dd></div><div><dt>Evidence</dt><dd>{{ $application->upfrontPayment->evidence }}</dd></div><div><dt>Recorded by</dt><dd>{{ $application->upfrontPayment->recorder->name }}</dd></div></dl></div>@endif
@if($application->loan)<div class="panel"><h2>Approved loan</h2><a class="button" href="/loans/{{ $application->loan->public_id }}">👁 View loan profile</a></div>@elseif($application->status==='submitted' && in_array(auth()->user()->role,['admin','financier']))<div class="panel no-print"><h2>Application decision</h2><div class="decision-actions"><form action="/applications/{{ $application->public_id }}/approve" method="POST">@csrf<button aria-label="Approve application" title="Approve application">✓ Approve</button></form><details><summary class="danger-action" title="Reject application">✕ Reject</summary><form action="/applications/{{ $application->public_id }}/reject" method="POST">@csrf<label>Reason for rejection<textarea name="reason" required></textarea></label><button class="danger">✕ Confirm rejection</button></form></details></div></div>@endif
<a href="/applications">← Back to applications</a>
@endsection
