@extends('layout')
@section('title','Customer profile')
@section('content')
<div class="section-head"><div><div class="eyebrow">CUSTOMER PROFILE</div><h1>{{ $customer->name }}</h1><p class="subtitle">Customer information, product qualification, and borrowing history.</p></div><a class="button secondary" href="/customers">← Customers</a></div>
<div class="grid two">
 <article class="card"><small>Submeter qualifying amount</small><div class="stat">{{ number_format($customer->submeter_qualifying_amount) }} TZS</div><small>Default 100,000 TZS</small></article>
 <article class="card"><small>Token qualifying amount</small><div class="stat">{{ number_format($customer->token_qualifying_amount) }} TZS</div><small>Default 5,000 TZS</small></article>
</div>
<div class="grid two customer-profile-layout"><section class="panel customer-info"><div class="customer-identity"><div class="customer-avatar">{{ strtoupper(substr($customer->first_name?:$customer->name,0,1).substr($customer->last_name?:strrchr($customer->name,' ')?:'',0,1)) }}</div><div><div class="eyebrow">CUSTOMER INFORMATION</div><h2>{{ $customer->name }}</h2><span class="badge approved">Verified customer</span></div></div><div class="info-group"><h3>Contact details</h3><div class="info-grid"><div><small>Primary phone</small><strong>{{ $customer->phone }}</strong></div><div><small>Alternative phone</small><strong>{{ $customer->alternative_phone ?: 'Not provided' }}</strong></div><div class="wide"><small>Email address</small><strong>{{ $customer->email ?: 'Not provided' }}</strong></div></div></div><div class="info-group"><h3>Identity & occupation</h3><div class="info-grid"><div><small>ID type</small><strong>{{ $customer->id_type ? ucwords(str_replace('_',' ',$customer->id_type)) : 'Not provided' }}</strong></div><div><small>ID number</small><strong>{{ $customer->id_number ?: 'Not provided' }}</strong></div><div><small>Occupation</small><strong>{{ $customer->occupation ?: 'Not provided' }}</strong></div><div><small>Gender</small><strong>{{ $customer->gender ? ucfirst($customer->gender) : 'Not provided' }}</strong></div></div></div><div class="info-group"><h3>Residential address</h3><div class="address-card"><strong>{{ $customer->address }}</strong><span>{{ collect([$customer->ward,$customer->district,$customer->region])->filter()->join(' · ') }}</span></div></div><div class="info-group"><h3>Next of kin</h3><div class="info-grid"><div><small>Full name</small><strong>{{ $customer->next_of_kin ?: 'Not provided' }}</strong></div><div><small>Phone number</small><strong>{{ $customer->next_of_kin_phone ?: 'Not provided' }}</strong></div></div></div><div class="customer-meta"><span>Onboarded by</span><strong>{{ $customer->onboardedBy?->name ?? 'Self-registered' }}</strong></div></section>
@if(auth()->user()->role==='admin')<section class="panel"><h2>Edit customer & qualification</h2><form method="POST" action="/customers/{{ $customer->public_id }}">@csrf @method('PUT')<label>Name<input name="name" value="{{ old('name',$customer->name) }}" required></label><label>Email <small class="muted">Optional</small><input type="email" name="email" value="{{ old('email',$customer->email) }}"></label><label>Phone<input name="phone" value="{{ old('phone',$customer->phone) }}" required></label><label>Submeter qualifying amount (TZS)<input type="number" name="submeter_qualifying_amount" min="0" value="{{ old('submeter_qualifying_amount',$customer->submeter_qualifying_amount) }}" required></label><label>Token qualifying amount (TZS)<input type="number" name="token_qualifying_amount" min="0" value="{{ old('token_qualifying_amount',$customer->token_qualifying_amount) }}" required></label><button>Save customer</button></form></section>@endif</div>
<section class="panel">
 <h2>Product qualification</h2>
 <div class="table-wrap"><table><thead><tr><th>Product</th><th>Category</th><th>Financing value</th><th>Customer limit</th><th>Loan count</th><th>Eligibility</th></tr></thead><tbody>
 @foreach($products as $product)
  @php
   $limit = $product->category === 'token' ? $customer->token_qualifying_amount : $customer->submeter_qualifying_amount;
   $count = $customer->applications->where('product_id', $product->id)->whereIn('status', ['submitted', 'approved'])->count();
   $eligible = $product->value <= $limit && $count < $product->max_loans_per_customer;
  @endphp
  <tr><td>{{ $product->name }}</td><td>{{ ucfirst($product->category) }}</td><td>{{ number_format($product->value) }} TZS</td><td>{{ number_format($limit) }} TZS</td><td>{{ $count }} / {{ $product->max_loans_per_customer }}</td><td><span class="badge {{ $eligible?'approved':'rejected' }}">{{ $eligible?'Qualifies':'Not qualified' }}</span></td></tr>
 @endforeach
 </tbody></table></div>
</section>
<section class="panel"><h2>Applications</h2><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Product</th><th>Status</th><th>Date</th></tr></thead><tbody>@forelse($customer->applications as $application)<tr><td><a href="/applications/{{ $application->public_id }}">{{ $application->reference }}</a></td><td>{{ $application->product->name }}</td><td><span class="badge {{ $application->status }}">{{ ucfirst($application->status) }}</span></td><td>{{ $application->created_at->format('d M Y') }}</td></tr>@empty<tr><td colspan="4">No applications yet.</td></tr>@endforelse</tbody></table></div></section>
@endsection
