@extends('layout')
@section('title','Disbursements')
@section('content')
<div class="section-head"><div><div class="eyebrow">DEVICE SETTLEMENTS</div><h1>Disbursements</h1><p class="subtitle">Consolidate paid-up devices into a daily batch, then book the bulk supplier payment.</p></div></div>
<div class="grid">@foreach($stats as $label=>$value)<article class="card"><span>{{ $label }}</span><strong>{{ $label === 'Total value' ? number_format($value).' TZS' : number_format($value) }}</strong><small>{{ $label === 'Total value' ? 'consolidated' : 'batches' }}</small></article>@endforeach</div>
<form class="panel filters" method="GET" action="/disbursements"><select name="status"><option value="">All statuses</option><option value="unpaid" @selected(request('status')==='unpaid')>Unpaid</option><option value="paid" @selected(request('status')==='paid')>Paid</option></select><button type="submit">Filter</button><a class="button secondary" href="/disbursements">Clear</a></form>
<section class="panel">
<div class="section-head"><div><h2>Eligible devices</h2><p class="muted">Only approved submeter loans with fully confirmed upfront payments appear here.</p></div><div class="batch-total"><small>Selected total</small><strong id="selected-total">0 TZS</strong></div></div>
<form method="POST" action="/disbursements/batches" id="batch-form">@csrf<div class="table-wrap"><table><thead><tr><th></th><th>Loan / customer</th><th>Device</th><th>Device serial</th><th>Amount</th></tr></thead><tbody>
@forelse($eligible as $loan)<tr><td><input class="batch-loan" type="checkbox" name="loan_ids[]" value="{{ $loan->id }}" data-amount="{{ $loan->terms['principal'] }}" aria-label="Select {{ $loan->reference }}"></td><td><a href="/loans/{{ $loan->public_id }}">{{ $loan->reference }}</a><br><strong>{{ $loan->customer->name }}</strong></td><td>{{ $loan->application->meter_brand_model ?: $loan->terms['product_name'] }}<br><small class="muted">{{ $loan->application->utility_type }}</small></td><td><input name="device_serials[{{ $loan->id }}]" value="{{ old('device_serials.'.$loan->id,$loan->application->device_serial) }}" placeholder="Required when selected"></td><td>{{ number_format($loan->terms['principal']) }} TZS</td></tr>@empty<tr><td colspan="5" class="empty">No paid-up devices are awaiting consolidation.</td></tr>@endforelse
</tbody></table></div>@if($eligible->isNotEmpty())<div class="batch-submit"><span class="muted"><span id="selected-count">0</span> device(s) selected</span><button>Create unpaid daily batch</button></div>@endif</form></section>
<div class="section-head"><h2>Daily batches</h2></div>
@forelse($batches as $batch)<article class="panel batch-card"><div class="section-head"><div><h2>{{ $batch->reference }}</h2><p class="muted">{{ $batch->batch_date->format('d M Y') }} · {{ $batch->items->count() }} device(s) · created by {{ $batch->creator->name }}</p></div><div class="batch-total"><span class="badge {{ $batch->status==='paid'?'confirmed':'pending' }}">{{ ucfirst($batch->status) }}</span><strong>{{ number_format($batch->total_amount) }} TZS</strong></div></div>
<details><summary>View consolidated devices</summary><div class="table-wrap"><table><thead><tr><th>Loan</th><th>Customer</th><th>Serial</th><th>Amount</th></tr></thead><tbody>@foreach($batch->items as $item)<tr><td><a href="/loans/{{ $item->loan->public_id }}">{{ $item->loan->reference }}</a></td><td>{{ $item->loan->customer->name }}</td><td>{{ $item->device_serial }}</td><td>{{ number_format($item->amount) }} TZS</td></tr>@endforeach</tbody></table></div></details>
@if($batch->status==='unpaid')<div class="payment-booking"><h3>Book bulk payment</h3><form method="POST" action="/disbursements/batches/{{ $batch->public_id }}/pay">@csrf<div class="grid two"><label>Payment reference<input name="payment_reference" required></label><label>Bank / payment institution<input name="institution" required></label><label>Account name<input name="account_name" required></label><label>Account number<input name="account_number" required></label><label>Payment date<input name="paid_at" type="date" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" required></label></div><button>Mark batch paid · {{ number_format($batch->total_amount) }} TZS</button></form></div>@else<div class="payment-proof"><strong>Paid {{ $batch->paid_at->format('d M Y') }}</strong><span>{{ $batch->payment_reference }} · {{ $batch->institution }}</span><span>{{ $batch->account_name }} · {{ $batch->account_number }}</span></div>@endif</article>@empty<div class="panel empty">No disbursement batches created yet.</div>@endforelse
@include('partials.pagination',['items'=>$batches])
<script>document.addEventListener('DOMContentLoaded',()=>{const boxes=[...document.querySelectorAll('.batch-loan')],total=document.getElementById('selected-total'),count=document.getElementById('selected-count');const update=()=>{const selected=boxes.filter(box=>box.checked);total.textContent=new Intl.NumberFormat('en-TZ').format(selected.reduce((sum,box)=>sum+Number(box.dataset.amount),0))+' TZS';if(count)count.textContent=selected.length};boxes.forEach(box=>box.addEventListener('change',update));update()});</script>
@endsection
