@extends('layout')
@section('content')
<h1>Payments</h1><p class="subtitle">Book and review customer payments.</p>
<div class="grid">@foreach($stats as $label=>$value)<div class="card"><small>{{ $label }}</small><div class="stat">{{ number_format($value) }}</div><small>payments</small></div>@endforeach</div>
@if(auth()->user()->role==='supplier')<div class="panel"><h2>Book a collected repayment</h2>@if($eligibleLoans->isEmpty())<p class="muted">There are no active or overdue loans eligible for repayment booking.</p>@else
<form method="POST" id="repayment-form">@csrf<input type="hidden" name="purpose" value="repayment"><div class="grid two"><label>Customer loan<select id="payment-loan" required><option value="">Choose an active loan</option>@foreach($eligibleLoans as $loan)<option value="{{ $loan->public_id }}">{{ $loan->reference }} · {{ $loan->customer->name }} · Outstanding {{ number_format($loan->outstanding()) }} TZS</option>@endforeach</select></label><label>Amount collected (TZS)<input name="amount" type="number" min="1" required></label><label>Payment channel<select name="channel"><option value="mobile_money">Mobile money</option><option value="bank">Bank transfer</option><option value="cash">Cash</option></select></label><label>Receipt<input name="reference" required></label><label>Payment date<input name="paid_at" type="date" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" required></label></div><button>Book repayment</button></form>
<script>document.addEventListener('DOMContentLoaded',()=>{const f=document.getElementById('repayment-form'),l=document.getElementById('payment-loan');l.addEventListener('change',()=>f.action=l.value?'/loans/'+l.value+'/payments':'')});</script>@endif</div>@endif
<form class="filters" method="GET"><input name="q" placeholder="Payment reference" value="{{ request('q') }}"><select name="status"><option value="">All statuses</option>@foreach(['pending','confirmed','reversed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button>Filter</button><a class="button quiet" href="/payments">Clear</a></form>
@include('partials.payment-table') @include('partials.pagination',['items'=>$payments])
@endsection
