@extends('layout')
@section('title','Supplier payouts')
@section('content')
@php($canBook=auth()->user()->role==='admin')
<div class="section-head"><div><div class="eyebrow">SUPPLIER SETTLEMENTS</div><h1>Supplier payouts</h1><p class="subtitle">{{ $canBook?'Select pending loan payouts and book one consolidated supplier payment.':'Track the payouts generated from your customer loans.' }}</p></div></div>
<div class="grid payout-summary">@foreach($stats as $label=>$value)<article class="card"><small>{{ $label }}</small><div class="stat">{{ number_format($value) }}</div><small>{{ str_contains(strtolower($label),'amount')?'TZS':'records' }}</small></article>@endforeach</div>
<form class="panel filters" method="GET"><input name="q" placeholder="Loan reference or customer" value="{{ request('q') }}"><select name="status"><option value="">All statuses</option><option value="pending" @selected(request('status')==='pending')>Pending</option><option value="paid" @selected(request('status')==='paid')>Paid</option></select><button>Filter</button><a class="button quiet" href="/payouts">Clear</a></form>
@if($canBook)
<form method="POST" action="/payouts/book">
@csrf
@endif
<section class="panel"><div class="section-head"><div><h2>Payout entries</h2><p class="muted">Each approved loan creates one supplier payout entry.</p></div>@if($canBook)<strong id="selected-total">0 TZS selected</strong>@endif</div><div class="table-wrap"><table><thead><tr>@if($canBook)<th><input type="checkbox" id="select-all" aria-label="Select all pending payouts"></th>@endif<th>Loan / customer</th><th>Product</th><th>Installation</th><th>Amount</th><th>Disbursement reference</th><th>Status</th></tr></thead><tbody>
@forelse($payouts as $payout)<tr>@if($canBook)<td>@if($payout->status==='pending')<input class="payout-check" type="checkbox" name="payout_ids[]" value="{{ $payout->id }}" data-amount="{{ $payout->amount }}">@endif</td>@endif<td><a href="/loans/{{ $payout->loan->public_id }}"><strong>{{ $payout->loan->reference }}</strong></a><br><small>{{ $payout->loan->customer->name }}</small></td><td>{{ ucfirst($payout->loan->terms['category']??'Loan') }}</td><td><span class="badge {{ $payout->loan->installation_status }}">{{ str_replace('_',' ',ucfirst($payout->loan->installation_status)) }}</span></td><td>{{ number_format($payout->amount) }} TZS</td><td>@if($payout->status==='paid' && $payout->batch)<strong>{{ $payout->batch->payment_reference }}</strong><br><small>{{ $payout->batch->reference }}</small>@else<span class="muted">—</span>@endif</td><td><span class="badge {{ $payout->status }}">{{ ucfirst($payout->status) }}</span>@if($payout->paid_at)<br><small>{{ $payout->paid_at->format('d M Y') }}</small>@endif</td></tr>@empty<tr><td colspan="{{ $canBook?7:6 }}" class="empty">No payout entries found.</td></tr>@endforelse
</tbody></table></div>@include('partials.pagination',['items'=>$payouts])</section>
@if($canBook)
<section class="panel"><h2>Book consolidated disbursement</h2><p class="muted">The selected total is paid as one transaction and updates every linked loan.</p><div class="grid two"><label>Payment reference<input name="payment_reference" required></label><label>Bank / payment institution<input name="institution" required></label><label>Account name<input name="account_name" required></label><label>Account number<input name="account_number" required></label><label>Payment date<input name="paid_at" type="date" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" required></label></div><button id="book-button" disabled>Book selected payout</button></section>
</form>
<script>const c=[...document.querySelectorAll('.payout-check')],a=document.querySelector('#select-all'),t=document.querySelector('#selected-total'),b=document.querySelector('#book-button');function s(){const x=c.filter(e=>e.checked),n=x.reduce((v,e)=>v+Number(e.dataset.amount),0);t.textContent=new Intl.NumberFormat().format(n)+' TZS selected';b.disabled=!x.length;if(a)a.checked=c.length>0&&x.length===c.length}c.forEach(e=>e.addEventListener('change',s));if(a)a.addEventListener('change',()=>{c.forEach(e=>e.checked=a.checked);s()});s();</script>
<section class="panel"><div class="section-head"><div><h2>Platform commissions</h2><p class="muted">Booked separately from supplier payouts.</p></div></div><div class="table-wrap"><table><thead><tr><th>Loan</th><th>Commission</th><th>Status</th><th>Reference / action</th></tr></thead><tbody>@forelse($payouts->where('platform_commission_amount','>',0) as $commission)<tr><td><a href="/loans/{{ $commission->loan->public_id }}">{{ $commission->loan->reference }}</a></td><td><strong>{{ number_format($commission->platform_commission_amount) }} TZS</strong></td><td><span class="badge {{ $commission->platform_commission_status==='booked'?'paid':'pending' }}">{{ ucfirst($commission->platform_commission_status) }}</span></td><td>@if($commission->platform_commission_status==='pending')<form class="inline" method="POST" action="/payouts/{{ $commission->id }}/commission">@csrf<input name="reference" placeholder="Booking reference" required><input name="booked_at" type="date" max="{{ today()->toDateString() }}" value="{{ today()->toDateString() }}" required><button>Book</button></form>@else<strong>{{ $commission->platform_commission_reference }}</strong><br><small>{{ $commission->platform_commission_booked_at?->format('d M Y') }}</small>@endif</td></tr>@empty<tr><td colspan="4" class="empty">No platform commissions on this page.</td></tr>@endforelse</tbody></table></div></section>
@endif
@endsection
