@extends('layout')
@section('content')
<h1>Loan products</h1><p class="subtitle">Configure pricing, customer loan limits, availability, and approval mode.</p>
<div class="grid">@foreach($stats as $label=>$value)<div class="card"><small>{{ $label }}</small><div class="stat">{{ number_format($value) }}</div><small>products</small></div>@endforeach</div>
<form class="filters" method="GET"><input name="q" placeholder="Product name or code" value="{{ request('q') }}"><select name="status"><option value="">All statuses</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select><button>Filter</button><a class="button quiet" href="/products">Clear</a></form>
<div class="panel table-wrap"><table><thead><tr><th>Product</th><th>Value</th><th>Principal</th><th>Term</th><th>Loans/customer</th><th>Approval</th><th>Status</th><th></th></tr></thead><tbody>@forelse($products as $p)<tr><td>{{ $p->name }}<br><small>{{ $p->code }}</small></td><td>{{ number_format($p->value) }}</td><td>{{ number_format($p->principal) }}</td><td>{{ $p->installments }} months</td><td>{{ $p->max_loans_per_customer }}</td><td>{{ $p->auto_approve?'Automatic':'Manual' }}</td><td>{{ $p->active?'Active':'Inactive' }}</td><td><a href="/products/{{ $p->public_id }}/edit">✎ Edit</a></td></tr>@empty<tr><td colspan="8" class="empty">No matching products.</td></tr>@endforelse</tbody></table></div>
@include('partials.pagination',['items'=>$products])
<div class="panel"><h2>{{ $editing?'Edit product':'Register a product' }}</h2><form method="POST" action="{{ $editing?'/products/'.$editing->public_id:'/products' }}">@csrf @if($editing)@method('PUT')@endif
<div class="grid two"><label>Product name<input name="name" value="{{ old('name',$editing?->name) }}" required></label><label>Unique code<input name="code" value="{{ old('code',$editing?->code) }}" required></label><label>Category<select name="category">@foreach(['submeter','token','other'] as $category)<option @selected(old('category',$editing?->category)===$category)>{{ $category }}</option>@endforeach</select></label><label>Installments<input name="installments" type="number" min="1" max="60" value="{{ old('installments',$editing?->installments??1) }}" required></label><label>Maximum loans per customer<input name="max_loans_per_customer" type="number" min="1" max="100" value="{{ old('max_loans_per_customer',$editing?->max_loans_per_customer??1) }}" required></label></div>
<label>Description<textarea name="description" required>{{ old('description',$editing?->description) }}</textarea></label><div class="grid">@foreach(['value'=>'Purchase value','down_payment'=>'Down payment','commission'=>'Platform commission','principal'=>'Financier principal','finance_charge'=>'Finance charge'] as $key=>$label)<label>{{ $label }} (TZS)<input name="{{ $key }}" type="number" min="0" value="{{ old($key,$editing?->$key??0) }}" required></label>@endforeach</div>
<label><input type="checkbox" name="commission_financed" value="1" @checked(old('commission_financed',$editing?->commission_financed))>Finance platform commission</label><label class="check-label"><input type="checkbox" name="auto_approve" value="1" @checked(old('auto_approve',$editing?->auto_approve))><strong>Auto-approve applications</strong></label><label><input type="checkbox" name="active" value="1" @checked(old('active',$editing?->active))>Active</label><button>Save product</button></form></div>
@endsection
