<?php
namespace Tests\Feature;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\{Product,Financier,User,LoanApplication,Loan,Payment,Allocation};
use App\Services\LendingService;
use Illuminate\Validation\ValidationException;
class LendingTest extends TestCase {
 use RefreshDatabase;
 private User $admin; private User $customer; private Financier $financier;private LendingService $service;
 protected function setUp():void {parent::setUp();$this->seed();$this->admin=User::create(['name'=>'Admin','email'=>'admin@example.test','password'=>'test-password-long','role'=>'admin']);$this->customer=User::create(['name'=>'Customer','email'=>'customer@example.test','password'=>'test-password-long']);$this->financier=Financier::create(['name'=>'Test MFI','active'=>true]);$this->service=app(LendingService::class);$this->travelTo(\Carbon\Carbon::parse('2026-03-01'));}
 private function loan(string $code='SUBMETER'):Loan {$p=Product::where('code',$code)->first();$p->update(['active'=>true]);$this->financier->products()->syncWithoutDetaching([$p->id]);$a=LoanApplication::create(['reference'=>'APP-'.uniqid(),'user_id'=>$this->customer->id,'product_id'=>$p->id,'financier_id'=>$this->financier->id,'phone'=>'255700000000','id_number'=>'TEST-ID','address'=>'Dar es Salaam','terms'=>$p->quote(),'accepted_at'=>now()]);return $this->service->approve($a,$this->admin);}
 private function pay(Loan $l,int $amount,string $purpose='repayment'):Payment {$p=Payment::create(['loan_id'=>$l->id,'reference'=>'PAY-'.uniqid(),'purpose'=>$purpose,'amount'=>$amount,'channel'=>'bank','evidence'=>'Verified bank receipt','recorded_by'=>$this->admin->id,'paid_at'=>now()]);$this->service->confirm($p,$this->admin);return $p;}
 private function disburse(Loan $l,string $date='2026-01-31'):void {$this->service->disburse($l,$this->admin,['amount'=>$l->terms['principal'],'reference'=>'DIS-'.$l->id,'recipient'=>'Supplier','device_serial'=>'SERIAL-1','date'=>$date]);}
 public function test_initial_product_terms_are_exact():void {$s=Product::where('code','SUBMETER')->first()->quote();$this->assertSame(45000,$s['upfront']);$this->assertSame(60000,$s['principal']);$this->assertSame(75000,$s['repayment_total']);$this->assertSame(120000,$s['upfront']+$s['repayment_total']);$t=Product::where('code','TOKEN')->first()->quote();$this->assertSame(0,$t['upfront']);$this->assertSame(5500,$t['principal']);$this->assertSame(6500,$t['repayment_total']);}
 public function test_disbursement_requires_confirmed_upfront():void {$l=$this->loan();$this->expectException(ValidationException::class);$this->disburse($l);}
 public function test_schedule_is_created_on_approval_and_disbursement_retries_are_correct():void {$this->travelTo(\Carbon\Carbon::parse('2026-01-31'));$l=$this->loan();$s=$l->installments()->get();$this->assertSame('pending_disbursement',$l->fresh()->status);$this->assertCount(3,$s);$this->assertSame(['2026-02-28','2026-03-31','2026-04-30'],$s->map(fn($x)=>$x->due_date->toDateString())->all());$this->pay($l,45000,'upfront');$this->disburse($l);$this->disburse($l);$this->assertCount(3,$l->installments);$this->assertSame(60000,(int)$s->sum('principal'));$this->assertSame(15000,(int)$s->sum('charge'));$again=$this->service->approve($l->application,$this->admin);$this->assertSame($l->id,$again->id);$this->assertSame(1,Loan::count());}
 public function test_partial_payment_duplicate_confirmation_and_full_payment():void {$l=$this->loan();$this->pay($l,45000,'upfront');$this->disburse($l);$p=$this->pay($l,10000);$this->service->confirm($p,$this->admin);$this->assertSame(65000,$l->outstanding());$s=$l->installments()->first();$this->assertSame(8000,(int)$s->paid_principal);$this->assertSame(2000,(int)$s->paid_charge);$this->pay($l,65000);$this->assertSame(0,$l->outstanding());$this->assertSame('paid',$l->fresh()->status);}
 public function test_product_edits_preserve_loan_snapshot():void {$l=$this->loan();Product::where('code','SUBMETER')->update(['finance_charge'=>30000]);$this->assertSame(15000,$l->fresh()->terms['finance_charge']);}
 public function test_supplier_loan_profile_hides_financier_and_internal_charge_breakdown():void {$supplier=User::create(['name'=>'Supplier','email'=>'supplier-profile@example.test','password'=>'test-password-long','role'=>'supplier']);$this->customer->update(['onboarded_by'=>$supplier->id]);$l=$this->loan();$this->actingAs($supplier)->get('/loans/'.$l->id)->assertOk()->assertSee('Device price')->assertSee('100,000')->assertDontSee('Test MFI')->assertDontSee('Platform commission:')->assertDontSee('Finance charge: 15,000');}
 public function test_supplier_loan_list_hides_financier():void {$supplier=User::create(['name'=>'Supplier','email'=>'supplier-list@example.test','password'=>'test-password-long','role'=>'supplier']);$this->customer->update(['onboarded_by'=>$supplier->id]);$l=$this->loan();$this->actingAs($supplier)->get('/loans')->assertOk()->assertSee($l->reference)->assertDontSee('Test MFI');}
 public function test_admin_consolidates_devices_as_unpaid_then_books_bulk_disbursement():void {$l=$this->loan();$this->pay($l,45000,'upfront');$this->actingAs($this->admin)->post('/disbursements/batches',['loan_ids'=>[$l->id],'device_serials'=>[$l->id=>'BULK-SERIAL-1']])->assertRedirect('/disbursements');$batch=\App\Models\DisbursementBatch::firstOrFail();$this->assertSame('unpaid',$batch->status);$this->assertSame(60000,(int)$batch->total_amount);$this->assertSame('pending_disbursement',$l->fresh()->status);$this->assertCount(3,$l->installments);$this->post('/disbursements/batches/'.$batch->id.'/pay',['payment_reference'=>'BULK-PAY-001','institution'=>'CRDB Bank','account_name'=>'Device Supplier Ltd','account_number'=>'0150000000000','paid_at'=>'2026-03-01'])->assertRedirect('/disbursements');$this->assertSame('paid',$batch->fresh()->status);$this->assertSame('active',$l->fresh()->status);$this->assertSame($batch->id,$l->disbursement->disbursement_batch_id);}
 public function test_supplier_can_edit_owned_submitted_application_but_not_after_approval():void {$supplier=User::create(['name'=>'Supplier','email'=>'supplier-edit@example.test','password'=>'test-password-long','role'=>'supplier']);$this->customer->update(['onboarded_by'=>$supplier->id,'date_of_birth'=>'1990-01-01','gender'=>'female','region'=>'Dar es Salaam','district'=>'Kinondoni','ward'=>'Mikocheni','address'=>'Old address','occupation'=>'Trader','next_of_kin'=>'Kin','next_of_kin_phone'=>'255700000009']);$product=Product::where('code','SUBMETER')->first();$application=LoanApplication::create(['reference'=>'APP-EDIT-1','user_id'=>$this->customer->id,'product_id'=>$product->id,'financier_id'=>$this->financier->id,'phone'=>'255700000000','id_number'=>'ID-OLD','address'=>'Old installation','supplier'=>$supplier->name,'utility_type'=>'electricity','device_price'=>100000,'meter_brand_model'=>'OLD MODEL','quotation_attached'=>true,'terms'=>$product->quote(),'accepted_at'=>now()]);$this->actingAs($supplier)->get('/applications/'.$application->id.'/edit')->assertOk();$payload=['name'=>'Edited Customer','email'=>$this->customer->email,'phone'=>'255700000011','alternative_phone'=>'255700000012','id_number'=>'ID-NEW','date_of_birth'=>'1990-01-01','gender'=>'female','region'=>'Dar es Salaam','district'=>'Kinondoni','ward'=>'Mikocheni','customer_address'=>'New address','occupation'=>'Business owner','next_of_kin'=>'New Kin','next_of_kin_phone'=>'255700000013','utility_type'=>'electricity','device_price'=>110000,'meter_brand_model'=>'NEW MODEL','device_serial'=>'EDIT-SERIAL','installation_address'=>'New installation','installation_date'=>'2026-03-01','quotation_attached'=>1];$this->put('/applications/'.$application->id,$payload)->assertRedirect('/applications/'.$application->id);$this->assertSame('ID-NEW',$application->fresh()->id_number);$this->assertSame('Edited Customer',$this->customer->fresh()->name);$this->service->approve($application->fresh(),$this->admin);$this->actingAs($supplier)->get('/applications/'.$application->id.'/edit')->assertForbidden();$this->put('/applications/'.$application->id,$payload)->assertForbidden();}
 public function test_auto_approve_product_creates_loan_schedule_and_pending_upfront_payment():void {$supplier=User::create(['name'=>'Supplier','email'=>'supplier-auto@example.test','password'=>'test-password-long','role'=>'supplier']);$this->customer->update(['onboarded_by'=>$supplier->id]);$product=Product::where('code','SUBMETER')->first();$product->update(['active'=>true,'auto_approve'=>true]);$this->financier->products()->attach($product);$application=LoanApplication::create(['reference'=>'APP-AUTO-1','user_id'=>$this->customer->id,'product_id'=>$product->id,'financier_id'=>$this->financier->id,'phone'=>'255700000000','id_number'=>'AUTO-ID','address'=>'Installation','supplier'=>$supplier->name,'utility_type'=>'electricity','device_price'=>100000,'meter_brand_model'=>'MODEL','quotation_attached'=>true,'terms'=>$product->quote(),'accepted_at'=>now()]);\App\Models\ApplicationUpfrontPayment::create(['application_id'=>$application->id,'amount'=>45000,'reference'=>'AUTO-UPFRONT-1','channel'=>'cash','evidence'=>'Receipt','paid_at'=>now(),'recorded_by'=>$supplier->id]);$loan=$this->service->approve($application,$supplier,true);$this->assertSame('approved',$application->fresh()->status);$this->assertCount(3,$loan->installments);$this->assertDatabaseHas('payments',['loan_id'=>$loan->id,'reference'=>'AUTO-UPFRONT-1','status'=>'pending']);}
 public function test_token_loan_and_overpayment():void {$l=$this->loan('TOKEN');$this->disburse($l);$this->assertCount(1,$l->installments);$this->assertSame(6500,$l->outstanding());$this->expectException(ValidationException::class);$this->pay($l,6501);}
 public function test_reversal_restores_debt_and_preserves_lines():void {$l=$this->loan('TOKEN');$this->disburse($l);$p=$this->pay($l,6500);$second=User::create(['name'=>'Second','email'=>'second@example.test','password'=>'test-password-long','role'=>'admin']);$this->service->reverse($p,$second,'Payment voided by bank');$this->assertSame(6500,$l->outstanding());$this->assertSame(0,(int)Allocation::where('payment_id',$p->id)->sum('amount'));$this->assertSame('reversed',$p->fresh()->status);}
 public function test_same_admin_cannot_reverse_their_confirmation():void {$l=$this->loan('TOKEN');$this->disburse($l);$p=$this->pay($l,6500);$this->expectException(ValidationException::class);$this->service->reverse($p,$this->admin,'Mistake');}
 public function test_customer_and_financier_isolation_and_role_routes():void {$l=$this->loan();$other=User::create(['name'=>'Other','email'=>'other@example.test','password'=>'test-password-long']);$this->actingAs($other)->get('/loans/'.$l->id)->assertForbidden();$this->actingAs($this->customer)->get('/products')->assertForbidden();$otherMfi=Financier::create(['name'=>'Other MFI']);$financierUser=User::create(['name'=>'MFI user','email'=>'mfi@example.test','password'=>'test-password-long','role'=>'financier','financier_id'=>$otherMfi->id]);$this->actingAs($financierUser)->get('/loans/'.$l->id)->assertForbidden();$this->actingAs($financierUser)->get('/reports/portfolio.csv')->assertOk()->assertDontSee($l->reference);}
 public function test_pending_payment_does_not_change_balances():void {$l=$this->loan('TOKEN');$this->disburse($l);Payment::create(['loan_id'=>$l->id,'reference'=>'PENDING','purpose'=>'repayment','amount'=>1000,'channel'=>'bank','evidence'=>'Unverified','recorded_by'=>$this->admin->id,'paid_at'=>now()]);$this->assertSame(6500,$l->outstanding());}
 public function test_all_admin_and_customer_pages_render():void {$l=$this->loan();foreach(['/dashboard','/applications','/applications/'.$l->application_id,'/loans','/loans/'.$l->id,'/payments','/reports','/disbursements','/products','/products/1/edit','/financiers','/financiers/'.$this->financier->id.'/edit','/users','/audit'] as $path)$this->actingAs($this->admin)->get($path)->assertOk();$this->actingAs($this->customer)->get('/apply/1')->assertOk();$this->get('/')->assertOk();}
 public function test_public_registration_cannot_escalate_role():void {$this->post('/register',['name'=>'Attacker','email'=>'new@example.test','phone'=>'255700000001','password'=>'strong-password-123','password_confirmation'=>'strong-password-123','role'=>'admin','financier_id'=>$this->financier->id])->assertRedirect('/dashboard');$this->assertSame('customer',User::where('email','new@example.test')->first()->role);}
 public function test_supplier_can_onboard_customer_submit_application_and_book_repayment():void {$supplier=User::create(['name'=>'Meter Supplier','email'=>'supplier@example.test','password'=>'test-password-long','role'=>'supplier']);$product=Product::where('code','SUBMETER')->first();$product->update(['active'=>true]);$this->financier->products()->attach($product);$this->actingAs($supplier)->get('/customers')->assertOk();$this->post('/customers',['name'=>'New Customer','email'=>'onboarded@example.test','phone'=>'255700000002','alternative_phone'=>'255700000003','id_number'=>'19900101-12345-00001-00','date_of_birth'=>'1990-01-01','gender'=>'female','region'=>'Dar es Salaam','district'=>'Kinondoni','ward'=>'Mikocheni','address'=>'House 12, Mikocheni','occupation'=>'Shop owner','next_of_kin'=>'Kin Name','next_of_kin_phone'=>'255700000004','product_id'=>$product->id,'utility_type'=>'electricity','device_price'=>100000,'meter_brand_model'=>'LIPACHAP','device_serial'=>'SERIAL-NEW','installation_address'=>'Shop 4, Mikocheni','installation_date'=>'2026-03-15','quotation_attached'=>1,'accepted'=>1,'terms_hash'=>hash('sha256',json_encode($product->quote())),'upfront_amount'=>45000,'upfront_reference'=>'ONBOARD-UPFRONT-1','upfront_channel'=>'cash','upfront_paid_at'=>'2026-03-01','upfront_evidence'=>'Supplier receipt'])->assertRedirect('/applications');$customer=User::where('email','onboarded@example.test')->firstOrFail();$this->assertSame('customer',$customer->role);$this->assertSame($supplier->id,$customer->onboarded_by);$this->assertSame('Mikocheni',$customer->ward);$application=LoanApplication::where('user_id',$customer->id)->firstOrFail();$this->assertSame($this->financier->id,$application->financier_id);$this->actingAs($supplier)->get('/applications')->assertOk()->assertSee($application->reference)->assertDontSee($this->financier->name);$loan=$this->service->approve($application,$this->admin);$upfront=$loan->payments()->where('purpose','upfront')->firstOrFail();$this->service->confirm($upfront,$this->admin);$this->disburse($loan);$this->actingAs($supplier)->get('/loans/'.$loan->id)->assertOk()->assertSee('Book repayment');$this->post('/loans/'.$loan->id.'/payments',['purpose'=>'repayment','amount'=>25000,'reference'=>'SUPPLIER-COLLECTION-1','channel'=>'cash','evidence'=>'Supplier collection receipt','paid_at'=>'2026-03-01'])->assertRedirect();$this->assertDatabaseHas('payments',['loan_id'=>$loan->id,'recorded_by'=>$supplier->id,'status'=>'confirmed']);$this->assertSame(50000,$loan->outstanding());$this->get('/users')->assertForbidden();$this->get('/reports')->assertForbidden();$this->actingAs($this->customer)->get('/customers')->assertForbidden();}
 public function test_application_requires_acceptance_and_current_terms():void {$p=Product::where('code','TOKEN')->first();$p->update(['active'=>true]);$this->financier->products()->attach($p);$this->actingAs($this->customer)->post('/apply/'.$p->id,['financier_id'=>$this->financier->id,'phone'=>'255700000000','id_number'=>'ID','address'=>'Dar','meter_number'=>'123','accepted'=>1,'terms_hash'=>'stale'])->assertSessionHasErrors('accepted');$this->assertSame(0,LoanApplication::count());}
 public function test_customer_application_to_confirmed_payment_http_journey():void {
 $p=Product::where('code','TOKEN')->first();$p->update(['active'=>true]);$this->financier->products()->attach($p);
 $this->actingAs($this->customer)->post('/apply/'.$p->id,['financier_id'=>$this->financier->id,'phone'=>'255700000000','id_number'=>'ID','address'=>'Dar','meter_number'=>'12345','accepted'=>1,'terms_hash'=>hash('sha256',json_encode($p->quote()))])->assertRedirect('/applications');
 $a=LoanApplication::first();$this->actingAs($this->admin)->post('/applications/'.$a->id.'/approve')->assertRedirect();$l=Loan::first();
 $this->post('/loans/'.$l->id.'/disburse',['amount'=>5500,'reference'=>'VERIFIED-DIS','recipient'=>'Token supplier','date'=>'2026-03-01'])->assertSessionHasNoErrors();
 $this->post('/loans/'.$l->id.'/payments',['purpose'=>'repayment','amount'=>6500,'reference'=>'VERIFIED-PAY','channel'=>'bank','evidence'=>'Bank receipt 123','paid_at'=>'2026-03-01'])->assertSessionHasNoErrors();$pay=Payment::first();$this->assertSame(6500,$l->outstanding());
 $this->post('/payments/'.$pay->id.'/confirm')->assertSessionHasNoErrors();$this->assertSame('paid',$l->fresh()->status);
 $this->actingAs($this->customer)->get('/payments/'.$pay->id.'/receipt')->assertOk()->assertSee('VERIFIED-PAY');
 }
}
