<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('financiers',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('registration')->nullable();$t->text('address')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('password');$t->string('phone')->nullable();$t->string('role')->default('customer');$t->foreignId('financier_id')->nullable()->constrained()->restrictOnDelete();$t->rememberToken();$t->timestamps();});
  Schema::create('products',function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->string('category');$t->text('description');$t->unsignedBigInteger('value');$t->unsignedBigInteger('down_payment');$t->unsignedBigInteger('commission');$t->boolean('commission_financed')->default(false);$t->unsignedBigInteger('principal');$t->unsignedBigInteger('finance_charge');$t->unsignedInteger('installments');$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('financier_product',function(Blueprint $t){$t->foreignId('financier_id')->constrained()->restrictOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->unique(['financier_id','product_id']);});
  Schema::create('applications',function(Blueprint $t){$t->id();$t->string('reference')->unique();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('product_id')->constrained()->restrictOnDelete();$t->foreignId('financier_id')->constrained()->restrictOnDelete();$t->string('phone');$t->string('id_number');$t->text('address');$t->string('meter_number')->nullable();$t->string('supplier')->nullable();$t->json('terms');$t->timestamp('accepted_at');$t->string('status')->default('submitted')->index();$t->text('decision_reason')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamps();});
  Schema::create('loans',function(Blueprint $t){$t->id();$t->string('reference')->unique();$t->foreignId('application_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('user_id')->constrained()->restrictOnDelete();$t->foreignId('financier_id')->constrained()->restrictOnDelete();$t->json('terms');$t->string('status')->default('pending_disbursement')->index();$t->string('device_serial')->nullable();$t->timestamp('disbursed_at')->nullable();$t->timestamps();});
  Schema::create('disbursements',function(Blueprint $t){$t->id();$t->foreignId('loan_id')->unique()->constrained()->restrictOnDelete();$t->unsignedBigInteger('amount');$t->string('reference')->unique();$t->string('recipient');$t->foreignId('confirmed_by')->constrained('users')->restrictOnDelete();$t->timestamp('confirmed_at');$t->timestamps();});
  Schema::create('installments',function(Blueprint $t){$t->id();$t->foreignId('loan_id')->constrained()->restrictOnDelete();$t->unsignedInteger('number');$t->date('due_date')->index();$t->unsignedBigInteger('principal');$t->unsignedBigInteger('charge');$t->unsignedBigInteger('paid_principal')->default(0);$t->unsignedBigInteger('paid_charge')->default(0);$t->string('status')->default('pending');$t->timestamps();$t->unique(['loan_id','number']);});
  Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('loan_id')->constrained()->restrictOnDelete();$t->string('reference')->unique();$t->string('purpose');$t->unsignedBigInteger('amount');$t->string('channel');$t->string('status')->default('pending');$t->text('evidence');$t->foreignId('recorded_by')->constrained('users')->restrictOnDelete();$t->foreignId('confirmed_by')->nullable()->constrained('users')->restrictOnDelete();$t->timestamp('paid_at');$t->timestamp('confirmed_at')->nullable();$t->text('reversal_reason')->nullable();$t->timestamps();});
  Schema::create('allocations',function(Blueprint $t){$t->id();$t->foreignId('payment_id')->constrained()->restrictOnDelete();$t->foreignId('installment_id')->nullable()->constrained()->restrictOnDelete();$t->string('component');$t->bigInteger('amount');$t->foreignId('reversal_of')->nullable()->constrained('allocations')->restrictOnDelete();$t->timestamps();});
  Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->restrictOnDelete();$t->string('action');$t->string('entity');$t->unsignedBigInteger('entity_id');$t->json('metadata')->nullable();$t->timestamps();});
 }
 public function down(): void {foreach(['audit_logs','allocations','payments','installments','disbursements','loans','applications','financier_product','products','users','financiers'] as $table) Schema::dropIfExists($table);}
};
