<?php
namespace App\Http\Controllers;
use App\Models\{Product,Financier,LoanApplication,Loan,Payment,Installment,AuditLog};
use App\Services\{Visibility,LendingService};
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class MarketplaceController {
 public function home(){return view('home',['products'=>Product::where('active',true)->get()]);}
 public function dashboard(Request $r){$loans=Visibility::scope(Loan::query(),$r->user());$ids=(clone $loans)->pluck('id');$applications=Visibility::scope(LoanApplication::query(),$r->user());$s=Installment::whereIn('loan_id',$ids);$payments=Payment::whereIn('loan_id',$ids)->where('status','confirmed');return view('dashboard',['loans'=>(clone $loans)->with('customer','financier')->withSum(['payments as paid_amount'=>fn($q)=>$q->where('purpose','repayment')->where('status','confirmed')],'amount')->latest()->limit(6)->get(),'cards'=>['Applications pending'=>(clone $applications)->where('status','submitted')->count(),'Active loans'=>(clone $loans)->whereIn('status',['active','overdue'])->count(),'Principal disbursed'=>DB::table('disbursements')->whereIn('loan_id',$ids)->sum('amount'),'Repayments received'=>(clone $payments)->where('purpose','repayment')->sum('amount'),'Outstanding debt'=>(clone $s)->selectRaw('COALESCE(SUM(principal+charge-paid_principal-paid_charge),0) AS total')->value('total'),'Overdue debt'=>(clone $s)->where('due_date','<',today())->selectRaw('COALESCE(SUM(principal+charge-paid_principal-paid_charge),0) AS total')->value('total')]]);}
 public function apply(Product $product){abort_unless($product->active,404);return view('apply',['product'=>$product,'financiers'=>$product->financiers()->where('active',true)->get()]);}
 public function submit(Request $r,Product $product){abort_unless($product->active,404);$v=$r->validate(['financier_id'=>'required|integer','phone'=>'required|string|max:30','id_number'=>'required|string|max:80','address'=>'required|string|max:1000','meter_number'=>($product->category==='token'?'required':'nullable').'|string|max:80','supplier'=>($product->category==='submeter'?'required':'nullable').'|string|max:150','terms_hash'=>'required|string','accepted'=>'accepted']);abort_unless($product->financiers()->where('financiers.id',$v['financier_id'])->where('active',true)->exists(),422);$customer=$r->user();$qualifying=(int)($product->category==='token'?$customer->token_qualifying_amount:$customer->submeter_qualifying_amount);if((int)$product->value>$qualifying)throw ValidationException::withMessages(['accepted'=>'This product exceeds your '.number_format($qualifying).' TZS qualifying amount.']);$count=LoanApplication::where('user_id',$customer->id)->where('product_id',$product->id)->whereIn('status',['submitted','approved'])->count();if($count>=(int)$product->max_loans_per_customer)throw ValidationException::withMessages(['accepted'=>'You have reached the maximum of '.$product->max_loans_per_customer.' loan(s) for this product.']);$terms=$product->quote();if(!hash_equals(hash('sha256',json_encode($terms)),$v['terms_hash']))throw ValidationException::withMessages(['accepted'=>'Product terms have changed. Reload and review them before applying.']);unset($v['accepted'],$v['terms_hash']);$a=LoanApplication::create($v+['reference'=>'APP-'.Str::upper(Str::random(10)),'user_id'=>$customer->id,'product_id'=>$product->id,'terms'=>$terms,'accepted_at'=>now()]);AuditLog::create(['user_id'=>$customer->id,'action'=>'application.submitted','entity'=>'LoanApplication','entity_id'=>$a->id]);return redirect('/applications')->with('success','Application submitted.');}
 public function applications(Request $r){$base=Visibility::scope(LoanApplication::query(),$r->user());$stats=['Total'=>(clone $base)->count(),'Submitted'=>(clone $base)->where('status','submitted')->count(),'Approved'=>(clone $base)->where('status','approved')->count(),'Rejected'=>(clone $base)->where('status','rejected')->count()];$q=Visibility::scope(LoanApplication::with('customer','product','loan'),$r->user());if($r->filled('status'))$q->where('status',$r->status);if($r->filled('q'))$q->where(fn($x)=>$x->where('reference','like','%'.$r->q.'%')->orWhereHas('customer',fn($u)=>$u->where('name','like','%'.$r->q.'%')));return view('applications',['applications'=>$q->latest()->paginate(20)->withQueryString(),'stats'=>$stats]);}
 public function application(Request $r,LoanApplication $application){Visibility::check($application,$r->user());$application->load('customer.onboardedBy','financier','product','loan','upfrontPayment.recorder');return view('application',compact('application'));}
 public function approve(Request $r,LoanApplication $application,LendingService $s){$loan=$s->approve($application,$r->user());return redirect('/loans/'.$loan->public_id)->with('success','Application approved. Record upfront payment before disbursement where required.');}
 public function reject(Request $r,LoanApplication $application,LendingService $s){$v=$r->validate(['reason'=>'required|string|max:1000']);$s->reject($application,$r->user(),$v['reason']);return back()->with('success','Application rejected.');}
 public function loans(Request $r){$base=Visibility::scope(Loan::query(),$r->user());$stats=['Total'=>(clone $base)->count(),'Active'=>(clone $base)->where('status','active')->count(),'Overdue'=>(clone $base)->where('status','overdue')->count(),'Paid'=>(clone $base)->where('status','paid')->count()];$q=Visibility::scope(Loan::with('customer','financier')->withSum(['payments as paid_amount'=>fn($payment)=>$payment->where('purpose','repayment')->where('status','confirmed')],'amount'),$r->user());if($r->filled('status'))$q->where('status',$r->input('status'));if($r->filled('q'))$q->where(fn($x)=>$x->where('reference','like','%'.$r->q.'%')->orWhereHas('customer',fn($u)=>$u->where('name','like','%'.$r->q.'%')));return view('loans',['loans'=>$q->latest()->paginate(20)->withQueryString(),'stats'=>$stats]);}
 public function loan(Request $r,Loan $loan){Visibility::check($loan,$r->user());$loan->load('customer','financier','application','installments','payments','disbursement');return view('loan',compact('loan'));}
 public function disburse(Request $r,Loan $loan,LendingService $s){$v=$r->validate(['amount'=>'required|integer|min:1','reference'=>'required|string|max:150','recipient'=>'required|string|max:150','device_serial'=>'nullable|string|max:100','date'=>'required|date|before_or_equal:today']);$s->disburse($loan,$r->user(),$v);return back()->with('success','Disbursement confirmed and schedule generated.');}
 public function confirmInstallation(Request $r,Loan $loan,LendingService $s){$v=$r->validate(['device_serial'=>'required|string|max:100','installation_address'=>'required|string|max:1000','installation_date'=>'required|date|before_or_equal:today']);$s->confirmInstallation($loan,$r->user(),$v);return back()->with('success','Installation confirmed. The loan is now awaiting disbursement.');}
 public function recordPayment(Request $r,Loan $loan,LendingService $s){Visibility::check($loan,$r->user());$v=$r->validate(['purpose'=>'required|in:upfront,repayment','amount'=>'required|integer|min:1|max:1000000000','reference'=>'required|string|max:150|unique:payments','channel'=>'required|in:bank,mobile_money,cash','paid_at'=>'required|date|before_or_equal:today']);$v['evidence']='Receipt: '.$v['reference'];if(($v['purpose']==='upfront' && $loan->disbursement_status!=='pending')||($v['purpose']==='repayment'&&!in_array($loan->status,['active','overdue'])))throw ValidationException::withMessages(['purpose'=>'Payment purpose is not valid for this loan state.']);$payment=Payment::create($v+['loan_id'=>$loan->id,'recorded_by'=>$r->user()->id]);if($r->user()->role==='supplier'&&$v['purpose']==='repayment'){$s->confirm($payment,$r->user());return back()->with('success','Repayment booked and applied to the loan schedule.');}return back()->with('success','Payment recorded pending administrator confirmation.');}
 public function payments(Request $r){$loanScope=Visibility::scope(Loan::query(),$r->user());$ids=(clone $loanScope)->pluck('id');$base=Payment::whereIn('loan_id',$ids);$stats=['Total'=>(clone $base)->count(),'Pending'=>(clone $base)->where('status','pending')->count(),'Confirmed'=>(clone $base)->where('status','confirmed')->count(),'Reversed'=>(clone $base)->where('status','reversed')->count()];$q=Payment::with('loan.customer')->whereIn('loan_id',$ids);if($r->filled('status'))$q->where('status',$r->status);if($r->filled('q'))$q->where('reference','like','%'.$r->q.'%');$eligibleLoans=(clone $loanScope)->with('customer')->whereIn('status',['active','overdue'])->latest()->get();return view('payments',['payments'=>$q->latest()->paginate(20)->withQueryString(),'eligibleLoans'=>$eligibleLoans,'stats'=>$stats]);}
 public function confirm(Request $r,Payment $payment,LendingService $s){$s->confirm($payment,$r->user());return back()->with('success','Payment confirmed.');}
 public function reverse(Request $r,Payment $payment,LendingService $s){$v=$r->validate(['reason'=>'required|string|max:1000']);$s->reverse($payment,$r->user(),$v['reason']);return back()->with('success','Payment reversed with an audit trail.');}
 public function receipt(Request $r,Payment $payment){Visibility::check($payment->loan,$r->user());return view('receipt',compact('payment'));}
 public function reports(Request $r){$ids=Visibility::scope(Loan::query(),$r->user())->pluck('id');$totals=DB::table('allocations')->join('payments','payments.id','=','allocations.payment_id')->whereIn('payments.loan_id',$ids)->selectRaw('component,SUM(allocations.amount) AS total')->groupBy('component')->get();return view('reports',['totals'=>$totals]);}
 public function export(Request $r){$loans=Visibility::scope(Loan::with('customer','financier','installments'),$r->user())->get();return response()->streamDownload(function()use($loans){$f=fopen('php://output','w');fputcsv($f,['Loan','Customer','Financier','Status','Principal','Repayment total','Outstanding']);foreach($loans as $l){$safe=fn($x)=>preg_match('/^[=+@\\-\\t\\r]/',(string)$x)?"'".$x:$x;fputcsv($f,array_map($safe,[$l->reference,$l->customer->name,$l->financier->name,$l->status,$l->terms['principal'],$l->terms['repayment_total'],$l->outstanding()]));}fclose($f);},'loan-portfolio.csv',['Content-Type'=>'text/csv']);}
}
